spring:
  profiles:
    active: ${APP_PROFILE:jpa}
  main:
    banner-mode: off

server:
  port: 10000

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

stripe:
  api-key: ${STRIPE_API_KEY}
  webhook-secret: ${WEBHOOK_SECRET}
  success-url: ${STRIPE_SUCCESS_URL:http://localhost:${PORT:10000}/api/payments/success?session_id={CHECKOUT_SESSION_ID}}
  cancel-url: ${STRIPE_CANCEL_URL:http://localhost:${PORT:10000}/api/payments/cancel}